import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
class Game implements ActionListener{
	Frame f;
	Button b[][]=new Button[8][8];
	int i,j,k,l;
	int hit=0,count=0;
	int n[]=new int[64];
	int r[]=new int[64];
	int d1[]=new int[64];
	Label li1,li2;
	TextField t1,t2;
	Game()
	{
		f=new Frame("Break The Box");
		Color c=new Color(100,200,150);
		f.setBackground(Color.black);
		f.setLayout(null);
		li1=new Label("Hit");
		li1.setForeground(Color.white);
		li1.setBounds(20,500,100,40);
		f.add(li1);
		li2=new Label("Success");
		li2.setForeground(Color.white);
		li2.setBounds(20,550,100,40);
		f.add(li2);
		t1=new TextField();
		t1.setBounds(220,500,100,20);
		f.add(t1);
		t2=new TextField();
		t2.setBounds(220,550,100,20);
		f.add(t2);
		for(i=0;i<8;i++)
		{
			for(j=0;j<8;j++)
			{
		b[i][j]=new Button();
		b[i][j].setBackground(Color.pink);
		b[i][j].setBounds(50+(50*j),50+(50*i),50,50);
		f.add(b[i][j]);
		}
		}
	
		for(i=0;i<8;i++)
		{
			for(j=0;j<8;j++)
			{
				b[i][j].addActionListener(this);
			}
		}
		for(i=0;i<8;i++)
		{
			for(j=0;j<8;j++)
			{
				b[i][j].setEnabled(true);
			}
		}
		f.setSize(800,600);
		f.setVisible(true);
		
	}
	public void actionPerformed(ActionEvent ae)
	{
		
		Object ob=ae.getSource();
		if(ob==b[0][0])
		{
			b[0][0].setLabel("9");
		
		}
		if(ob==b[0][1])
		{
			b[0][1].setLabel("1");
		}
		if(ob==b[0][2])
		{
			b[0][2].setLabel("8");
		}
		if(ob==b[0][3])
		{
		b[0][3].setLabel("4");
		}
		if(ob==b[0][4])
		{
		b[0][4].setLabel("2");
		}
		if(ob==b[0][5])
		{
			b[0][5].setLabel("7");
		}
		if(ob==b[0][6])
		{
		b[0][6].setLabel("3");
		}
		if(ob==b[0][7])
		{
		b[0][7].setLabel("2");
		}
		if(ob==b[1][0])
		{
		b[1][0].setLabel("9");
		}
		if(ob==b[1][1])
		{
		b[1][1].setLabel("0");
		}
		if(ob==b[1][2])
		{
		b[1][2].setLabel("9");
		}
		if(ob==b[1][3])
		{
		b[1][3].setLabel("1");
		}
		if(ob==b[1][4])
		{
		b[1][4].setLabel("7");
		}
		if(ob==b[1][5])
		{
		b[1][5].setLabel("3");
		}
		if(ob==b[1][6])
		{
			b[1][6].setLabel("9");
		}
		if(ob==b[1][7])
		{
			b[1][7].setLabel("1");
		}
		if(ob==b[2][0])
		{
			b[2][0].setLabel("5");
		}
		if(ob==b[2][1])
		{
		b[2][1].setLabel("6");
		}
		if(ob==b[2][2])
		{
		b[2][2].setLabel("6");
		}
		if(ob==b[2][3])
		{
			b[2][3].setLabel("0");
		}
		if(ob==b[2][4])
		{
			b[2][4].setLabel("6");
		}
		if(ob==b[2][5])
		{
		b[2][5].setLabel("8");
		}
		if(ob==b[2][6])
		{
		b[2][6].setLabel("6");	
		}
		if(ob==b[2][7])
		{
		b[2][7].setLabel("1");
		}
		if(ob==b[3][0])
		{
		b[3][0].setLabel("8");
		}
		if(ob==b[3][1])
		{
		b[3][1].setLabel("8");
		}
		if(ob==b[3][2])
		{
		b[3][2].setLabel("7");
		}
		if(ob==b[3][3])
		{
		b[3][3].setLabel("9");
		}
		if(ob==b[3][4])
		{
			b[3][4].setLabel("9");
		}
		if(ob==b[3][5])
		{			
		b[3][5].setLabel("7");
		}
		if(ob==b[3][6])
		{
		b[3][6].setLabel("3");
		}
		if(ob==b[3][7])
		{
		b[3][7].setLabel("5");
		}
		if(ob==b[4][0])
		{
		b[4][0].setLabel("7");
		}
		if(ob==b[4][1])
		{	
		b[4][1].setLabel("2");
		}
		if(ob==b[4][2])
		{
		b[4][2].setLabel("4");
		}
		if(ob==b[4][3])
		{
		b[4][3].setLabel("7");
		}
		if(ob==b[4][4])
		{
		b[4][4].setLabel("9");
		}
		if(ob==b[4][5])
		{
		b[4][5].setLabel("1");
		}
		if(ob==b[4][6])
		{
		b[4][6].setLabel("3");
		}
		if(ob==b[4][7])
		{
		b[4][7].setLabel("0");
		}
		if(ob==b[5][0])
		{
		b[5][0].setLabel("4");
		}
		if(ob==b[5][1])
		{
		b[5][1].setLabel("4");
		}
		if(ob==b[5][2])
		{
			b[5][2].setLabel("4");
		}
		if(ob==b[5][3])
		{
		b[5][3].setLabel("5");
		}
		if(ob==b[5][4])
		{
		b[5][4].setLabel("1");
		}
		if(ob==b[5][5])
		{
		b[5][5].setLabel("5");
		}
		if(ob==b[5][6])
		{
		b[5][6].setLabel("9");
		}
		if(ob==b[5][7])
		{
			b[5][7].setLabel("0");
		}
		if(ob==b[6][0])
		{
			b[6][0].setLabel("0");
		}
		if(ob==b[6][1])
		{
		b[6][1].setLabel("8");
		}
		if(ob==b[6][2])
		{
		b[6][2].setLabel("6");
		}
		if(ob==b[6][3])
		{
		b[6][3].setLabel("2");
		}
		if(ob==b[6][4])
		{
			b[6][4].setLabel("8");
		}
		if(ob==b[6][5])
		{
		b[6][5].setLabel("4");
		}
		if(ob==b[6][6])
		{
		b[6][6].setLabel("6");
		}
		if(ob==b[6][7])
		{
		b[6][7].setLabel("8");
		}
		if(ob==b[7][0])
		{
			b[7][0].setLabel("0");
		}
		if(ob==b[7][1])
		{
		b[7][1].setLabel("5");
		}
		if(ob==b[7][2])
		{
			b[7][2].setLabel("3");
		}
		if(ob==b[7][3])
		{
	     b[7][3].setLabel("5");
		}
		if(ob==b[7][4])
		{
			b[7][4].setLabel("2");
		
		}
		if(ob==b[7][5])
		{
		b[7][5].setLabel("3");
		
		}
		if(ob==b[7][6])
		{
		b[7][6].setLabel("2");
		
		}
		if(ob==b[7][7])
		{
		b[7][7].setLabel("8");
		}
	
		for(i=0;i<8;i++)
		{
			for(j=0;j<8;j++)
			{
				if(ob==b[i][j])
				{
					hit++;
					t1.setText(""+hit);
					r[hit]=i;
					n[hit]=j;
					b[i][j].setEnabled(false);
					d1[hit-1]=Integer.parseInt(b[i][j].getLabel());
					if(hit>1)
					{
							for(k=0;k<hit-1;k++)
							{
								if(d1[hit-1]==d1[k])
								{				
									f.remove(b[i][j]);
									f.remove(b[r[k+1]][n[k+1]]);
									d1[hit-1]=10;
									d1[k]=10;		
								}
							}
					}
				}
			}
		}
	}
	public static void main(String z[]){
		Game a=new Game();
	}
}